### ISSUE TITLE
Missing menu item in tray menu on GNOME 3.28.1

### ISSUE THREAD

**Issue by sz-k** [alexcroox/jira-timer-menubar#6]
The tray icon is visible, but not the menu item, though it's clickable (and opens the login window).

**Comment by alexcroox** [comment]
Hi @szkrd did you install the TopIcons extension? https://github.com/alexcroox/jira-timer-menubar/blob/master/README.md#linux-users

If yes, could you take a screenshot of what you see?

**Comment by szkrd** [comment]
I'm sorry, I'm not on linux anymore and we changed to gitlab :(
